version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=securitysentry

  backend:
    build: ./app
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./app:/app
    environment:
      - PYTHONPATH=/app

  frontend:
    build: ./client
    container_name: react-client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/client
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  mongo_data: